name: Setup
description: Sets up runner with Node, pnpm and install dependencies

runs:
  using: composite
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        run_install: false
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        cache: "pnpm"
        node-version-file: .nvmrc
    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile --prefer-offline
