name: release

on:
  workflow_dispatch:
    inputs:
      release:
        description: Release type
        required: true
        options:
          - patch
          - minor
          - major

permissions:
  contents: write

env:
  HUSKY: 0

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup system environment
        uses: ./.github/actions/setup
  check:
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup system environment
        uses: ./.github/actions/setup
      - name: Check
        run: pnpm check
  test:
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup system environment
        uses: ./.github/actions/setup
      - name: Test
        run: pnpm test
  build:
    runs-on: ubuntu-latest
    needs: [check, test]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup system environment
        uses: ./.github/actions/setup
      - name: Build
        run: pnpm build
      - name: Save artifacts
        uses: actions/cache/save@v4
        with:
          key: ${{ runner.os }}-dist-${{ github.run_id }}
          path: ./dist
  release-latest:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup system environment
        uses: ./.github/actions/setup
      - name: Get artifacts
        uses: actions/cache/restore@v4
        with:
          key: ${{ runner.os }}-dist-${{ github.run_id }}
          path: ./dist
          fail-on-cache-miss: true
      - name: Release latest version
        env:
          GITHUB_DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          RELEASE_TYPE: ${{ inputs.release }}
        run: node ./scripts/publish.js
      - name: Commit latest version
        run: |
          date > generated.txt
          # Note: the following account information will not work on GHES
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "chore: version bump"
          git push
